name: CI
on:
  push:
    branches-ignore:
      - 'save'
      - 'save-*'
  pull_request:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: |
          npm ci
          npm run build
          npm run test
